#!/bin/bash -e

DIR=`pwd`/`dirname $0`

# XSession script
sudo install $DIR/xsessions/default.desktop /usr/share/xsessions

# XMonad
sudo apt-get -y install cabal-install xmonad \
	libghc-gconf-dev libghc-missingh-dev

# Synapse
sudo apt-get -y install synapse zeitgeist-extension-fts

# IBus
#sudo apt-get -y install ibus ibus-pinyin ibus-table

# Session script
#sudo apt-get -y install feh
#sudo apt-get -y install notify-osd
#sudo apt-get -y purge notification-daemon
#killall -q notification-daemon

#gconftool -s /apps/gnome_settings_daemon/keybindings/www -t string ''
#gconftool -s /apps/gnome_settings_daemon/keybindings/email -t string ''

# http://stackoverflow.com/questions/1347105/linux-link-all-files-from-one-to-another-directory
find "/home/adamm/code/Dotfiles/home" -maxdepth 1 -printf "%P\n" |\
	grep -v '^\w*$' |\
	while read file; do \
		ln -sf "/home/adamm/code/Dotfiles/home/$file" "/home/adamm/$file"; \
	done

ln -sf "/home/adamm/code/Dotfiles/bin" "/home/adamm/bin"

sudo apt-get -y autoremove
